-- SKIL-2: the pack's skill-scan threshold (ADR-0052 decision 9).
--
-- One column, and deliberately nothing else. The *report* a reviewer
-- reads has no table here and will not get one: it is a pure function of
-- (file bytes, ruleset version), and both are already present wherever it
-- renders — the objects are read to draw the diff, and the rule table is
-- compiled into the binary. A row would buy a durable answer to "what did
-- the reviewer see" and would answer it worse than the audit chain does,
-- because a row is mutable and a chained event is not (ADR-0052
-- decision 6).
--
-- What a pack gets to say is one threshold: the severity at which a
-- bundle's scan refuses rather than reports. `{"block_at": "high"}` is
-- `regulated-strict`'s reading — a skill that shells out or writes
-- outside its bundle needs a rule change rather than a reviewer's
-- judgement. The relaxed packs stop at the floor.
--
-- What a pack cannot say is that `critical` is acceptable. The clamp is
-- in `SkillScanConfig::threshold`, on every read, for the reason
-- ADR-0032 decision 4 put the approval floor where it is: a pack may be
-- cheaper about how many people sign, and may not be cheaper about
-- whether the product ships a credential stealer. A stored pack that
-- names a threshold this column cannot express is treated as
-- unconfigured (the floor), like every other config on this table.

alter table policy_packs add column scan jsonb;
