//! Context-platform contract: the OpenAPI document is authoritative
//! (ADR-0071 decision 7; CPR-17/ADR-0082; CPR-18/ADR-0083;
//! CPR-23/ADR-0085; CPR-25/ADR-0086; CPR-27/ADR-0087).
//!
//! Three things have to be true for that sentence to mean anything, and this
//! suite is each of them:
//!
//! 1. **The committed document is the tree's document.** `docs/api/openapi.json`
//!    is derived from the handlers, so a DTO change that nobody regenerated is
//!    a failing test rather than a stale file somebody finds later.
//! 2. **Every documented path is actually mounted.** A contract that describes
//!    a route the router does not serve is worse than no contract: a client
//!    generated from it fails at runtime with a 404 it cannot explain.
//! 3. **The document does not quietly grow or shrink.** The macro that mounts
//!    `/v1` also emits its executable method/path catalogue; exact equality in
//!    both directions replaces the old hand-maintained expected-path list.
//!
//! Needs no database: every assertion is either pure or an unauthenticated
//! request that the tenant middleware refuses before anything opens a
//! connection. That is deliberate — the contract check must run in CI, and CI
//! has no Postgres.
//!
//! To refresh the document after changing a DTO or a handler annotation:
//!
//! ```sh
//! SYNVEDA_WRITE_OPENAPI=1 cargo test -p synveda-gateway --test openapi
//! node scripts/generate-api-types.mjs
//! ```

use std::sync::{Arc, OnceLock};
use std::time::Duration;

use axum::Router;
use axum::body::Body;
use axum::http::{Request, StatusCode};
use metrics_exporter_prometheus::PrometheusHandle;
use serde_json::Value;
use sqlx::postgres::PgPoolOptions;
use synveda_gateway::app::{AppState, behavior_test_router as router};
use synveda_gateway::{openapi, routes, telemetry};
use synveda_identity::Hs256Verifier;
use tower::ServiceExt;

/// The committed document, relative to the workspace root.
const DOCUMENT: &str = "../../docs/api/openapi.json";

const SECRET: &[u8] = b"cpr-4-openapi-test-secret";

/// A stand-in for the invitation token in `{invite_token}`. Deliberately not a
/// real one: this suite proves the route is mounted, and a request that got
/// past the tenant middleware is a different test.
const TOKEN_PLACEHOLDER: &str = "synveda_invite_v1.placeholder.placeholder";

fn metrics_handle() -> PrometheusHandle {
    static HANDLE: OnceLock<PrometheusHandle> = OnceLock::new();
    HANDLE
        .get_or_init(|| telemetry::init_metrics().expect("install prometheus recorder"))
        .clone()
}

/// A router over a pool that never connects. Every request this suite makes is
/// refused by the tenant middleware first, so the pool is never used — which
/// is what makes the whole suite runnable without a database.
fn app() -> Router {
    let state = AppState {
        pool: PgPoolOptions::new()
            .max_connections(1)
            .acquire_timeout(Duration::from_millis(50))
            .connect_lazy("postgres://unused:unused@127.0.0.1:1/unused")
            .expect("parse database url"),
        metrics: metrics_handle(),
        verifier: Arc::new(Hs256Verifier::new(SECRET)),
        login: None,
        public_origin: "http://127.0.0.1:8120".to_owned(),
        pdp: Arc::new(synveda_policy::Pdp::new().expect("build the embedded PDP")),
        service_token_max_ttl: Duration::from_secs(3600),
        embedder: Arc::new(synveda_ingest::embedding::AnyEmbedder::Deterministic(
            synveda_ingest::embedding::DeterministicEmbedder::new(),
        )),
        context_embed_timeout: Duration::from_millis(100),
        keys: Arc::new(synveda_store::keys::KeyRing::new(
            synveda_crypto::Kms::Disabled,
        )),
    };
    router(state)
}

/// The committed document must be the one this tree produces.
#[test]
fn the_committed_document_is_the_trees_document() {
    let derived = openapi::document();
    if std::env::var("SYNVEDA_WRITE_OPENAPI").is_ok() {
        std::fs::write(DOCUMENT, &derived).expect("write the OpenAPI document");
        eprintln!("wrote {DOCUMENT}");
        return;
    }
    let committed = std::fs::read_to_string(DOCUMENT).unwrap_or_else(|err| {
        panic!(
            "{DOCUMENT} is missing ({err}). Generate it with \
             `SYNVEDA_WRITE_OPENAPI=1 cargo test -p synveda-gateway --test openapi`"
        )
    });
    assert_eq!(
        committed, derived,
        "{DOCUMENT} is out of date with the handlers it describes. Refresh it with \
         `SYNVEDA_WRITE_OPENAPI=1 cargo test -p synveda-gateway --test openapi`, then \
         regenerate the frontend types with `node scripts/generate-api-types.mjs`."
    );
}

/// The generated contract and executable route catalogue agree exactly in
/// both directions. The catalogue itself is generated by the macro that
/// mounts the handlers, so this is not a second hand-maintained route list.
#[test]
fn contract_and_executable_application_routes_agree_exactly() {
    let declared = openapi::declared_operations();
    let mut executable: Vec<(String, String)> = routes::OPERATIONS
        .iter()
        .map(|operation| (operation.method.to_owned(), operation.path.to_owned()))
        .collect();
    executable.sort();
    assert_eq!(
        declared, executable,
        "the OpenAPI contract and the executable `/v1` route catalogue disagree"
    );
}

/// The equality check is authoritative only while the application router has
/// one `/v1` source. Pin that structural seam: a future direct route or merged
/// sibling must move into `routes.rs`, where it enters both inventories.
#[test]
fn the_application_router_mounts_only_the_catalogue() {
    let source = include_str!("../src/app.rs");
    assert!(source.contains("crate::routes::router()"));
    for forbidden in [
        concat!(".route(\"/", "v1"),
        concat!("credential_", "routes()"),
    ] {
        assert!(
            !source.contains(forbidden),
            "app.rs bypasses the executable catalogue through {forbidden}"
        );
    }
}

/// Every documented path is mounted on the router.
///
/// The evidence is the *status*: an unmounted path 404s from axum's own
/// matcher, and a mounted one behind the tenant middleware answers 401 for a
/// request with no credential. So 401 proves the route exists and 404 proves
/// the document is describing something the gateway does not serve.
#[tokio::test]
async fn every_documented_path_is_mounted() {
    let app = app();
    let id = uuid_placeholder();
    for (path, method) in documented_operations() {
        let concrete = path
            .replace("{workspace_id}", &id)
            .replace("{project_id}", &id)
            .replace("{repository_id}", &id)
            .replace("{invite_id}", &id)
            .replace("{grant_id}", &id)
            .replace("{group_id}", &id)
            .replace("{principal_id}", "sam")
            .replace("{session_id}", &id)
            .replace("{scope_id}", &id)
            .replace("{event_id}", &id)
            .replace("{version_id}", &id)
            .replace("{path}", "SKILL.md")
            .replace("{name}", "demo")
            .replace("{id}", &id)
            .replace("{invite_token}", TOKEN_PLACEHOLDER);
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method(method.as_str())
                    .uri(&concrete)
                    .body(Body::empty())
                    .expect("build request"),
            )
            .await
            .expect("router responds");
        assert_ne!(
            response.status(),
            StatusCode::NOT_FOUND,
            "{method} {path} is in the contract but not mounted on the router"
        );
        assert_eq!(
            response.status(),
            StatusCode::UNAUTHORIZED,
            "{method} {path} answered {} to an unauthenticated request; every \
             documented route sits behind the tenant middleware",
            response.status()
        );
    }
}

/// A path the document does not declare must not be reachable on this plane —
/// the same check from the other side, so a mounted-but-undocumented sibling
/// route is caught rather than assumed absent.
#[tokio::test]
async fn a_path_this_plane_does_not_declare_is_not_mounted() {
    let app = app();
    let id = uuid_placeholder();
    for path in [
        "/v1/workspaces/{workspace_id}/repositories",
        "/v1/projects",
        "/v1/workspaces/{workspace_id}/projects/{project_id}",
        // CPR-5 puts members on the project and invitations on the workspace,
        // deliberately and not symmetrically: a project is invited to through
        // the workspace that contains it, and a workspace's membership is
        // granted rather than added. The absent halves are checked here so the
        // asymmetry is a decision rather than an omission somebody fills in.
        "/v1/projects/{project_id}/invites",
        "/v1/workspaces/{workspace_id}/members/{principal_id}",
        "/v1/admin/groups/{group_id}/members",
        "/v1/proposals/{id}/classify",
    ] {
        let concrete = path
            .replace("{workspace_id}", &id)
            .replace("{project_id}", &id)
            .replace("{group_id}", &id)
            .replace("{principal_id}", "sam")
            .replace("{session_id}", &id)
            .replace("{id}", &id);
        let response = app
            .clone()
            .oneshot(
                Request::builder()
                    .method("GET")
                    .uri(&concrete)
                    .body(Body::empty())
                    .expect("build request"),
            )
            .await
            .expect("router responds");
        assert_eq!(
            response.status(),
            StatusCode::NOT_FOUND,
            "{path} is mounted but not on the contract"
        );
    }
}

/// The document is well formed in the ways the frontend generator depends on:
/// unique operation ids, a resolvable `$ref` everywhere, a declared security
/// scheme, and an error body on every 4xx.
#[test]
fn the_document_is_generatable() {
    let document: Value = serde_json::from_str(&openapi::document()).expect("valid JSON");
    let schemas = document["components"]["schemas"]
        .as_object()
        .expect("components.schemas");
    assert!(
        document["components"]["securitySchemes"]["bearer"].is_object(),
        "the bearer scheme must be declared once, for every path"
    );

    let mut operation_ids: Vec<String> = Vec::new();
    let mut refs: Vec<String> = Vec::new();
    collect_refs(&document, &mut refs);
    for reference in &refs {
        let name = reference
            .strip_prefix("#/components/schemas/")
            .unwrap_or_else(|| panic!("unexpected $ref target {reference}"));
        assert!(
            schemas.contains_key(name),
            "{reference} resolves to nothing; the generator would emit `unknown`"
        );
    }

    for (path, item) in document["paths"].as_object().expect("paths") {
        for (method, operation) in item.as_object().expect("path item") {
            let id = operation["operationId"]
                .as_str()
                .unwrap_or_else(|| panic!("{method} {path} has no operationId"));
            assert!(
                !operation_ids.contains(&id.to_owned()),
                "duplicate operationId {id:?}: the generated operation map would lose one"
            );
            operation_ids.push(id.to_owned());
            assert!(
                operation["security"].is_array(),
                "{method} {path} declares no security; every route here needs a bearer"
            );
            for (code, response) in operation["responses"].as_object().expect("responses") {
                if code.starts_with('4') {
                    assert_eq!(
                        response["content"]["application/json"]["schema"]["$ref"]
                            .as_str()
                            .unwrap_or_default(),
                        "#/components/schemas/ApiErrorBody",
                        "{method} {path} {code} must document the taxonomy body"
                    );
                }
            }
        }
    }
    assert_eq!(
        operation_ids.len(),
        routes::OPERATIONS.len(),
        "every executable application operation must have one unique generated operation id: \
         {operation_ids:?}"
    );
}

/// Every (path, method) pair the document declares.
fn documented_operations() -> Vec<(String, String)> {
    let document: Value = serde_json::from_str(&openapi::document()).expect("valid JSON");
    let mut pairs = Vec::new();
    for (path, item) in document["paths"].as_object().expect("paths") {
        for method in item.as_object().expect("path item").keys() {
            pairs.push((path.clone(), method.to_uppercase()));
        }
    }
    pairs
}

fn collect_refs(value: &Value, into: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            for (key, nested) in map {
                if key == "$ref"
                    && let Some(reference) = nested.as_str()
                {
                    into.push(reference.to_owned());
                }
                collect_refs(nested, into);
            }
        }
        Value::Array(items) => items.iter().for_each(|item| collect_refs(item, into)),
        _ => {}
    }
}

fn uuid_placeholder() -> String {
    synveda_types::TenantId::new().to_string()
}
