name: synveda-development

services:
  proxy:
    build:
      context: ../..
      dockerfile: deploy/compose/proxy/Dockerfile
    ports:
      - target: 8080
        published: ${SYNVEDA_DEV_HTTP_PORT:-8080}
        host_ip: 127.0.0.1
        protocol: tcp
  migrate:
    build:
      context: ../..
      dockerfile: deploy/compose/gateway/Dockerfile
  gateway:
    build:
      context: ../..
      dockerfile: deploy/compose/gateway/Dockerfile
  worker:
    build:
      context: ../..
      dockerfile: deploy/compose/gateway/Dockerfile
