# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict

from typing_extensions import TypedDict


class ApiErrorBody(TypedDict):
    action: NotRequired[str | None]
    entity: NotRequired[str | None]
    kind: str
    message: NotRequired[str | None]
    reason: NotRequired[str | None]
    resource: NotRequired[str | None]


class OpenSessionBody(TypedDict, closed=True):
    agent_name: NotRequired[str | None]
    branch: NotRequired[str | None]
    client_installation_id: NotRequired[str | None]
    client_name: str
    client_version: NotRequired[str | None]
    external_session_id: NotRequired[str | None]
    metadata: NotRequired[dict[str, Any] | None]
    model_name: NotRequired[str | None]
    project_id: NotRequired[str | None]
    repository_id: NotRequired[str | None]
    task_summary: NotRequired[str | None]
    workspace_id: str


class CreateContextRunBody(TypedDict, closed=True):
    budget_tokens: NotRequired[int | None]
    max_sensitivity: NotRequired[str | None]
    query: NotRequired[str | None]


class EndSessionBody(TypedDict, closed=True):
    end_reason: NotRequired[str | None]
    status: Literal['ending', 'ended', 'abandoned', 'failed']
    task_summary: NotRequired[str | None]


class KnowledgeQueryBody(TypedDict, closed=True):
    limit: NotRequired[int | None]
    query: str


class KnowledgeMutationView(TypedDict):
    change_id: str
    knowledge_item_id: NotRequired[str | None]
    operation_id: NotRequired[str | None]
    outcome: Literal['applied', 'pending_review', 'rejected']
    revision_id: NotRequired[str | None]


class SessionView(TypedDict):
    agent_name: NotRequired[str | None]
    branch: NotRequired[str | None]
    client_installation_id: NotRequired[str | None]
    client_name: str
    client_version: NotRequired[str | None]
    created_at: str
    end_reason: NotRequired[str | None]
    ended_at: NotRequired[str | None]
    external_session_id: NotRequired[str | None]
    id: str
    last_observed_at: NotRequired[str | None]
    metadata: dict[str, Any]
    model_name: NotRequired[str | None]
    principal_id: str
    project_id: NotRequired[str | None]
    repository_id: NotRequired[str | None]
    scope_id: str
    started_at: str
    status: Literal['active', 'ending', 'ended', 'abandoned', 'failed']
    task_summary: NotRequired[str | None]
    updated_at: str
    workspace_id: str


class CaptureBatchView(TypedDict):
    attempts: int
    candidate_count: int
    completed_at: NotRequired[str | None]
    configuration_hash: str
    configuration_version_id: NotRequired[str | None]
    created_at: str
    error_code: NotRequired[str | None]
    event_count: int
    extractor_method: NotRequired[str | None]
    id: str
    import_job_id: NotRequired[str | None]
    input_hash: str
    model_version: NotRequired[str | None]
    project_id: NotRequired[str | None]
    scope_id: str
    session_id: NotRequired[str | None]
    source_kind: Literal['session', 'okf_import']
    started_at: NotRequired[str | None]
    state: Literal['pending', 'running', 'completed', 'failed']


class ContextRunView(TypedDict):
    as_of: str
    block_hash: str
    budget_tokens: int
    candidate_count: int
    completion_status: str
    configuration_hash: str
    configuration_version_id: NotRequired[str | None]
    created_at: str
    degraded: list[str]
    embedding_model: NotRequired[str | None]
    entry_count: int
    graph_version: NotRequired[str | None]
    id: str
    index_version: str
    policy_exclusion_message: NotRequired[str | None]
    project_id: NotRequired[str | None]
    query: NotRequired[str | None]
    query_hash: NotRequired[str | None]
    rendered: NotRequired[str | None]
    requested_budget_tokens: NotRequired[int | None]
    retrieval_version: str
    scope_id: str
    selection_count: int
    session_id: str
    skills: dict[str, Any]
    tokens: int
    trace_retention_mode: str
    workspace_id: str


class SkillVersionView(TypedDict):
    bundle_digest: str
    created_at: str
    created_by: str
    declared_tools_are_authorization: bool
    id: str
    manifest: dict[str, Any]
    ordinal: int
    provenance: dict[str, Any]
    quality_score: int
    rubric_version: int
    scan: dict[str, Any]
    scan_ruleset_version: int
    sensitivity: Literal['public', 'internal', 'confidential', 'restricted']
    skill_id: str
    source_kind: Literal['authored', 'directory', 'archive', 'git', 'registry']


class SkillVersionFileContentView(TypedDict):
    content: str
    object_hash: str
    path: str
    version_id: str


class KnowledgeContentBody(TypedDict, closed=True):
    body_markdown: str
    confidence_permille: int
    metadata: NotRequired[dict[str, Any]]
    sensitivity: Literal['public', 'internal', 'confidential', 'restricted']
    stale_after: NotRequired[str | None]
    summary: str
    tags: NotRequired[list[str]]
    title: str
    valid_from: NotRequired[str | None]
    valid_to: NotRequired[str | None]
    verification_metadata: NotRequired[dict[str, Any]]


class AuditFrame(TypedDict):
    first_seq: NotRequired[int | None]
    head_hash: str
    head_seq: int
    last_seq: NotRequired[int | None]
    next_cursor: NotRequired[int | None]
    truncated: bool


class KnowledgeSourceBody(TypedDict, closed=True):
    content_hash: NotRequired[str | None]
    locator: NotRequired[str | None]
    metadata: NotRequired[dict[str, Any]]
    scope_id: NotRequired[str | None]
    session_event_id: NotRequired[str | None]
    source_revision: NotRequired[str | None]
    source_type: Literal[
        'session_event',
        'manual',
        'document',
        'repository',
        'url',
        'okf',
        'system_derived',
    ]


class TenantCapabilities(TypedDict):
    actions: dict[str, bool]
    role_keys: list[str]


class PrincipalView(TypedDict):
    display_name: NotRequired[str | None]
    identity_id: NotRequired[str | None]
    kind: NotRequired[str | None]
    quarantined: bool
    subject: str


class TenantView(TypedDict):
    id: str
    name: str
    slug: str
    status: str


class NewEventBody(TypedDict, closed=True):
    client_event_id: str
    event_schema_version: NotRequired[int]
    event_type: Literal[
        'session.started',
        'session.ended',
        'message.user',
        'message.assistant',
        'tool.invoked',
        'tool.result',
        'file.read',
        'file.changed',
        'command.executed',
        'skill.loaded',
        'context.requested',
        'adapter.warning',
        'memory.asserted',
    ]
    occurred_at: str
    payload: NotRequired[dict[str, Any] | None]


class AnchorCapabilities(TypedDict):
    actions: dict[str, bool]
    direct: bool
    kind: str
    roles: list[str]
    scope_id: str
    source: str


class ProjectView(TypedDict):
    created_at: str
    created_by: NotRequired[str | None]
    description: NotRequired[str | None]
    display_name: str
    id: str
    revision: int
    scope_id: str
    slug: str
    status: Literal['active', 'archived']
    updated_at: str
    workspace_id: str


class WorkspaceView(TypedDict):
    created_at: str
    created_by: NotRequired[str | None]
    description: NotRequired[str | None]
    display_name: str
    id: str
    revision: int
    scope_id: str
    slug: str
    status: Literal['active', 'archived']
    updated_at: str


class SkillVersionFileView(TypedDict):
    chars: int
    created_at: str
    object_hash: str
    path: str


class AuditEventView(TypedDict):
    action: str
    actor_kind: str
    actor_subject: str
    hash: str
    occurred_at: str
    outcome: str
    payload: Any
    resource: str
    seq: int
    trace_id: NotRequired[str | None]


OnboardingState: TypeAlias = Literal[
    'blocked', 'needs_workspace', 'needs_project', 'ready'
]


class ProposalApprovalView(TypedDict):
    approver_id: str
    approver_subject: str
    comment: NotRequired[str | None]
    commit: str
    counts: bool
    created_at: str
    roles: list[str]
    verdict: str


class ProposalTimelineEvent(TypedDict):
    actor_id: NotRequired[str | None]
    actor_subject: NotRequired[str | None]
    at: str
    commit: str
    kind: str
    reason: NotRequired[str | None]


class ProposalArtifactReference(TypedDict):
    artifact_id: str
    expected_revision: NotRequired[str | None]
    family: str
    operation: str
    version: str


class SkillBindingView(TypedDict):
    created_at: str
    created_by: str
    enabled: bool
    id: str
    pinned_version_id: NotRequired[str | None]
    revision: int
    scope_id: str
    skill_id: str
    updated_at: str
    updated_by: str


class KnowledgeSourceView(TypedDict):
    content_hash: NotRequired[str | None]
    created_at: str
    id: str
    locator: NotRequired[str | None]
    metadata: dict[str, Any]
    scope_id: str
    session_event_id: NotRequired[str | None]
    source_revision: NotRequired[str | None]
    source_type: Literal[
        'session_event',
        'manual',
        'document',
        'repository',
        'url',
        'okf',
        'system_derived',
    ]


ProposalMemberEffect: TypeAlias = Literal['add', 'update', 'apply', 'none']


class SessionEventView(TypedDict):
    client_event_id: str
    event_schema_version: int
    event_type: Literal[
        'session.started',
        'session.ended',
        'message.user',
        'message.assistant',
        'tool.invoked',
        'tool.result',
        'file.read',
        'file.changed',
        'command.executed',
        'skill.loaded',
        'context.requested',
        'adapter.warning',
        'memory.asserted',
    ]
    id: str
    occurred_at: str
    payload: dict[str, Any]
    payload_hash: str
    received_at: str
    sequence: int
    session_id: str


class ApprovalRoleView(TypedDict):
    count: int
    role: str


class KnowledgeRevisionView(TypedDict):
    body_markdown: str
    confidence_permille: int
    content_hash: str
    created_by: NotRequired[str | None]
    freshness_reasons: list[str]
    id: str
    knowledge_item_id: str
    metadata: dict[str, Any]
    revision_number: int
    sensitivity: Literal['public', 'internal', 'confidential', 'restricted']
    stale: bool
    stale_after: NotRequired[str | None]
    summary: str
    tags: list[str]
    title: str
    transaction_time: str
    valid_from: str
    valid_to: NotRequired[str | None]
    verification_metadata: dict[str, Any]


class ProposalBaselineView(TypedDict):
    object_hash: str
    text: str


class KnowledgeRelationView(TypedDict):
    asserting_revision_id: str
    created_at: str
    id: str
    metadata: dict[str, Any]
    relation_type: Literal[
        'supports',
        'duplicates',
        'contradicts',
        'supersedes',
        'derived_from',
        'references',
        'related_to',
        'transitions_to',
    ]
    source_item_id: str
    target_item_id: str


class CreateKnowledgeBody(TypedDict, closed=True):
    content: KnowledgeContentBody
    knowledge_type: Literal[
        'fact',
        'decision',
        'preference',
        'procedure',
        'entity',
        'episode',
        'convention',
        'warning',
        'reference',
    ]
    origin: NotRequired[Literal['observed', 'asserted', 'authored', 'imported']]
    owner_principal_id: NotRequired[str | None]
    project_id: NotRequired[str | None]
    scope_id: str
    sources: NotRequired[list[KnowledgeSourceBody]]


class AppendEventsBody(TypedDict, closed=True):
    events: list[NewEventBody]


class AuditEventsResponse(AuditFrame):
    events: list[AuditEventView]


class SkillVersionFileListView(TypedDict):
    files: list[SkillVersionFileView]


class OnboardingView(TypedDict):
    project_count: int
    state: OnboardingState
    tenant_scope_id: NotRequired[str | None]
    workspace_count: int


class AppendedEventView(TypedDict):
    client_event_id: str
    event: NotRequired[SessionEventView | None]
    outcome: str
    redactions: NotRequired[dict[str, Any] | None]


class AvailableSkillView(TypedDict):
    binding: SkillBindingView
    manifest_object_hash: str
    name: str
    version: SkillVersionView


class ApprovalRequirementView(TypedDict):
    distinct_approvers: int
    forbid_author_approval: bool
    origins: list[str]
    roles: list[ApprovalRoleView]
    separate_effect_actor: bool
    subjects: NotRequired[list[str]]


class ProposalMemberView(TypedDict):
    asset: str
    baseline: NotRequired[ProposalBaselineView | None]
    content: str
    effect: ProposalMemberEffect
    member: str
    object_hash: str
    proposed: str
    sensitivity: str
    unchanged: bool


class KnowledgeItemView(TypedDict):
    created_at: str
    created_by: NotRequired[str | None]
    current_revision: KnowledgeRevisionView
    id: str
    knowledge_type: Literal[
        'fact',
        'decision',
        'preference',
        'procedure',
        'entity',
        'episode',
        'convention',
        'warning',
        'reference',
    ]
    lifecycle_state: Literal[
        'active',
        'stale',
        'transitional',
        'superseded',
        'archived',
        'erasure_pending',
        'erased',
    ]
    match_score: NotRequired[float | None]
    origin: Literal['observed', 'asserted', 'authored', 'imported']
    owner_principal_id: NotRequired[str | None]
    project_id: NotRequired[str | None]
    relationships: NotRequired[list[KnowledgeRelationView]]
    scope_id: str
    updated_at: str
    updated_by: NotRequired[str | None]


class MeView(TypedDict):
    anchors: list[AnchorCapabilities]
    anchors_not_answered: NotRequired[int]
    capabilities: TenantCapabilities
    onboarding: OnboardingView
    principal: PrincipalView
    projects: list[ProjectView]
    tenant: TenantView
    workspaces: list[WorkspaceView]


class AppendResponse(TypedDict):
    appended: int
    denied: int
    duplicates: int
    events: list[AppendedEventView]
    quarantined: int


class AvailableSkillListView(TypedDict):
    scope_id: str
    skills: list[AvailableSkillView]


class ProposalSummary(TypedDict):
    artifact_references: list[ProposalArtifactReference]
    asset: str
    close_reason: NotRequired[str | None]
    closed_at: NotRequired[str | None]
    commit: str
    created_at: str
    effect: str
    id: str
    outstanding: str
    proposer_id: str
    proposer_subject: str
    required: ApprovalRequirementView
    sensitivity: str
    source_scope_id: str
    source_scope_path: NotRequired[str | None]
    state: str
    target_scope_id: str
    target_scope_path: NotRequired[str | None]
    title: str
    updated_at: str


class ContextKnowledgeView(TypedDict):
    knowledge: KnowledgeItemView
    sources: list[KnowledgeSourceView]


class ProposalDetail(ProposalSummary):
    approvals: list[ProposalApprovalView]
    members: list[ProposalMemberView]
    timeline: list[ProposalTimelineEvent]


class ContextKnowledgeQueryView(TypedDict):
    as_of: str
    degradation: NotRequired[str | None]
    items: list[ContextKnowledgeView]
    next_cursor: NotRequired[str | None]
    retrieval_mode: str
