# GENERATED by scripts/generate-sdk-contract.mjs.
from __future__ import annotations
from typing import Any
from . import models
from .client import Client, ApiResponse

async def list_audit_events(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.AuditEventsResponse]:
    return await client.request("list_audit_events", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def create_knowledge(client: Client, body: models.CreateKnowledgeBody, *, idempotency_key: str,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.KnowledgeMutationView]:
    return await client.request("create_knowledge", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def get_me(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.MeView]:
    return await client.request("get_me", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def get_proposal(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.ProposalDetail]:
    return await client.request("get_proposal", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def open_session(client: Client, body: models.OpenSessionBody, *, idempotency_key: str,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SessionView]:
    return await client.request("open_session", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def get_session(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SessionView]:
    return await client.request("get_session", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def create_capture_batch(client: Client, *, idempotency_key: str,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.CaptureBatchView]:
    return await client.request("create_capture_batch", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def create_context_run(client: Client, body: models.CreateContextRunBody, *, idempotency_key: str,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.ContextRunView]:
    return await client.request("create_context_run", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def end_session(client: Client, body: models.EndSessionBody, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SessionView]:
    return await client.request("end_session", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def append_session_events(client: Client, body: models.AppendEventsBody, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.AppendResponse]:
    return await client.request("append_session_events", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def query_session_knowledge(client: Client, body: models.KnowledgeQueryBody, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.ContextKnowledgeQueryView]:
    return await client.request("query_session_knowledge", body=body, path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def list_available_skills(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.AvailableSkillListView]:
    return await client.request("list_available_skills", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def get_skill_version(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SkillVersionView]:
    return await client.request("get_skill_version", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def list_skill_version_files(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SkillVersionFileListView]:
    return await client.request("list_skill_version_files", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)

async def get_skill_version_file(client: Client, *, idempotency_key: str | None = None,
    path: dict[str, str] | None = None, query: dict[str, str | int | bool | None] | None = None,
    traceparent: str | None = None) -> ApiResponse[models.SkillVersionFileContentView]:
    return await client.request("get_skill_version_file", path=path, query=query,
        idempotency_key=idempotency_key, traceparent=traceparent)
